language: java

sudo: true # faster builds with false

jdk:
    - oraclejdk8
    - oraclejdk7

install:
    true

before_script:
  - pip install --user codecov
  - curl http://www.jpm4j.org/install/script | sudo sh
  - sudo jpm install com.codacy:codacy-coverage-reporter:assembly

script:
  - jdk_switcher use oraclejdk8
    - mvn -U -B -V test --fail-at-end -Dsource.skip=true -Dmaven.javadoc.skip=true
  - jdk_switcher use oraclejdk7
    - mvn -U -B -V test --fail-at-end -Dsource.skip=true -Dmaven.javadoc.skip=true -pl !:hamcrest-extensions-jdk8

after_success:
  # JDK 8
  - jdk_switcher use oraclejdk8
  - mvn clean test jacoco:report coveralls:report
  - codecov -b "$TRAVIS_JOB_NUMBER-jdk8"
  # JDK 7
  - jdk_switcher use oraclejdk7
  - mvn clean test jacoco:report coveralls:report -pl !:hamcrest-extensions-jdk8
  - codecov -b "$TRAVIS_JOB_NUMBER-jdk7"
    # Codacy
  - mvn jacoco:report  -pl !:hamcrest-extensions-jdk8
  - export CODACY_PROJECT_TOKEN=b48fe5350c734384a74eca50cfc307cc
  - codacy-coverage-reporter -l Java -r coverage.xml
  - codacy-coverage-reporter -l Java -r target/site/jacoco/jacoco.xml --prefix src/main/java/
  - codacy-coverage-reporter -l Java -r hamcrest-extensions/hamcrest-extensions-jdk7/target/site/jacoco/jacoco.xml --prefix hamcrest-extensions/hamcrest-extensions-jdk7/src/main/java/

notifications:
    email:
      on_failure: change
